name: ML Run in Sequence
# on mentions a trigger for the workflow
on: 
    push: # when a push is made to the main branch of the repository
    #workflow_dispatch:  # run only when triggered manually
jobs:
  ml_run:
    runs-on: ubuntu-latest # runs the workflow on the latest ubuntu version
    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # uses the checkout action to checkout the code
      - name: Set up Python
        uses: actions/setup-python@v6 # uses the setup-python action to set up the python environment
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python ml_example.py
  deploy:    # this job runs completely on own runner 
    needs: ml_run # this job depends on the ml_run job
    runs-on: ubuntu-latest # runs the workflow on the latest ubuntu version
    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # uses the checkout action to checkout the code
      - name: Set up Python
        uses: actions/setup-python@v6 # uses the setup-python action to set up the python environment
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python ml_example.py
          
      - name: deploy
        run: echo 'deployment of the model'
